#!/usr/bin/perl
# Lab 5 - Program 13
# Many Secret Word Files In The Same Directory

# Joe O'Regan
# 26/02/2016

# Instead of just the file wordslist, include anything in the current directory that ends in .secret

init_words();
print "What is your name? ";
$name = <STDIN>;
chomp $name;
if ($name =~ /^randal\b/i) 
{ 							# back to the other way :-)
  print "Hello, Randal! How good of you to be here!\n";
} 
else 
{
  print "Hello, $name!\n"; 				# ordinary greeting
  print "What is the secret word? ";
  $guess = <STDIN>;
  chomp ($guess);
  while (! good_word($name,$guess)) 
  {
    print "Wrong, try again. What is the secret word? ";
    $guess = <STDIN>;
    chomp ($guess);
  }
}
## subroutines from here down
sub init_words 
{
  while ( defined($filename = glob("*.secret")) ) 	# reads in each file and
  {							# returns empty string when no more filenames
    open (WORDSLIST, $filename) ||
    die "can't open wordlist: $!";
    if (-M WORDSLIST < 7.0) 				# if wordlist older than a week, grouch is the
    {							# password for every name
      while ($name = <WORDSLIST>) 
      {
        chomp $name;
        $word = <WORDSLIST>;
        chomp $word;
        $words{$name} = $word;
      }
    }
    close (WORDSLIST) || die "couldn't close wordlist: $!";
  }
}							# loop exits when empty string returned

sub good_word 
{
  my($somename,$someguess) = @_; 				# name the parameters
  $somename =~ s/\W.*//;					# get rid of stuff after first word
  $somename =~ tr/A-Z/a-z/;					# lowercase everything
  if ($somename eq "randal") 
  {								# should not need to guess
    return 1;							# return value is true
  } 
  elsif (($words{$somename}||"groucho") eq $someguess) 
  {
    return 1;							# return value is true
  } 
  else 
  { 								#open MAIL,"|mail YOUR_ADDRESS_HERE";
    open MAIL,"|mail k00203642@student.lit.ie";
    print MAIL "bad news: $somename guessed $someguess\n";
    close MAIL;
    return 0;							# return value is false
  }
}

