#!/usr/bin/perl -w
# Lab 3 - Program 4
# Guessing The Secret Word

# NEW - While loops
# String Comparison & if-else statements

# Joe O'Regan
# 05/02/2016

$secretword = "llama"; 					# Scaler variable holds the secret word "llama"

print "What is your name? ";				# prompt user to enter name
$name = <STDIN>;					# user scaler variable "$name" to hold name, <STDIN> construct grabs one line of input
chomp $name;						# chomp removes trailing newline (\n) form input

if ($name eq "Randal") 					# if-then-else branch, eq compares if name string is equal to the string "Randal"
{
  print "Hello, Randal! How good of you to be here!\n";	# if name equals print this line, else go to next line
} 
else 
{
  print "Hello, $name!\n"; 				# Prints ordinary greeting when name is not Randal
  print "What is the secret word? ";			# NEW - Prompts user to enter the secret word
  $guess = <STDIN>;					# NEW - <STDIN> reads user input from keyboard
  chomp ($guess);

  while ($guess ne $secretword) 			# NEW - ne = Not Equal
  {							# NEW - While loop repeats question until correct answer entered
    print "Wrong, try again. What is the secret word? ";# NEW - if the user input #guess doesnt match #secretword, asks to try again
    $guess = <STDIN>;					# NEW - re-enter $guess
    chomp ($guess);					# NEW - remove trailing new line from $guess
  }
}

