#!/usr/bin/perl -w
# Lab 3 - Program 5
# More Than One Secret Word

# NEW - List / Array @<array-name>
# elsif, while loop and name compare

# Joe O'Regan
# 05/02/2016

@words = qw(camel llama alpaca);			# NEW - Array variables begin with @, so thery are distinct from scalar variable names
							# $words[0] = "camel", $words[1] = "llama", $words[2] = "alpaca"
print "What is your name? ";					
$name = <STDIN>;
chomp ($name);

if ($name eq "Randal") 
{
  print "Hello, Randal! How good of you to be here!\n";
} 
else 
{
  print "Hello, $name!\n";					# ordinary greeting
  print "What is the secret word? ";
  $guess = <STDIN>;
  chomp ($guess);

# $i: Access each element by using a subscript reference, $ 
  $i = 0; 							# try this word first
  $correct = "maybe";						# is the guess correct or not? NEW - $correct initialised to "maybe"

  while ($correct eq "maybe")
  {								# keep checking til we know
    if ($words[$i] eq $guess) 
    { 								# right?
      $correct = "yes";						# NEW yes! - Exit while loop if guess is equal to the array element
    } 
    elsif ($i < 2) 						# NEW - elsif, construct not present in all programming languages
    {								# NEW - more words to look at?
      $i = $i + 1;						# NEW - look at the next word next time, increment the elements
    } 
    else 
    {								# no more words, must be bad
      print "Wrong, try again. What is the secret word?";
      $guess = <STDIN>;
      chomp ($guess);
      $i = 0;							# NEW - start checking at the first word again, reset to 1st element
    }
  } # end of while not correct
} # end of "not Randal"

