#!/usr/bin/perl
while ( defined($filename = glob("*.secret")) ) {
  open (WORDSLIST, $filename) || die "can't open wordlist: $!";
  if (-M WORDSLIST < 7.0) {
    while ($name = <WORDSLIST>) {
      chomp ($name);
      $word = <WORDSLIST>;
      chomp ($word);
      write; # invoke format STDOUT to STDOUT
    }
  }
  close (WORDSLIST) || die "couldn't close wordlist: $!";
}
format STDOUT =
@<<<<<<<<<<<<<<< @<<<<<<<<< @<<<<<<<<<<<
$filename, $name, $word
.
