#!/usr/bin/perl
%words = qw(
fred
camel
barney
llama
betty
alpaca
wilma
alpaca
);
print "What is your name? ";
$name = <STDIN>;
chomp ($name);
$original_name = $name; #save for greeting
$name =~ s/\W.*//; # get rid of everything after first word
$name =~ tr/A-Z/a-z/; # lowercase everything
if ($name eq "randal") { # ok to compare this way now
print "Hello, Randal! How good of you to be here!\n";
} else {
print "Hello, $original_name!\n"; # ordinary greeting
$secretword = $words{$name}; # get the secret word
if ($secretword eq "") { # oops, not found
$secretword = "groucho"; # sure, why a duck?
}
print "What is the secret word? ";
$guess = <STDIN>;
chomp ($guess);
while ($guess ne $secretword) {
print "Wrong, try again. What is the secret word? ";
$guess = <STDIN>;
chomp ($guess);
}
}
