#!/usr/bin/perl -w
print "What is your name? ";	
# prompt user to enter name

$name = <STDIN>;		# user scaler variable "$name" to hold name, <STDIN> construct grabs one line of input

chomp ($name);			# chomp removes trailing newline (\n) form input

print "Hello, $name!\n";	# ouput to screen

