#!/usr/bin/perl
# Lab 5 - Program 14
# Listing The Secret Words

# Joe O'Regan
# 26/02/2016

# $% (number of pages printed), 

while ( defined($filename = glob("*.secret")) ) 
{
  open (WORDSLIST, $filename) || die "can't open wordlist: $!";
  if (-M WORDSLIST < 7.0) 
  {
    while ($name = <WORDSLIST>) 
    {
      chomp ($name);
      $word = <WORDSLIST>;
      chomp ($word);
      write; # invoke format STDOUT to STDOUT
    }
  }
  close (WORDSLIST) || die "couldn't close wordlist: $!";
}
format STDOUT =
@<<<<<<<<<<<<<<< @<<<<<<<<< @<<<<<<<<<<<
$filename, $name, $word
.
format STDOUT_TOP =						
Page @<<
$%								# $% variable - holds the page number
								# blank line - prints to screen as blank
Filename	 Name	    Word
================ ========== ============
.

