#!/usr/bin/perl -w 		# Comment, path to perl binary, -w give warnings
# Lab 2 - Program 1
# Hello World program

# Joe O'Regan
# 29/01/2016

print ("Hello, world!\n"); 	# prints Hello World to screen

