#!/usr/bin/perl
# Lab 3 - Program 6
# Giving Each Person A Different Secret Word

# NEW - Table / Hash

# Joe O'Regan
# 05/02/2016

# Hash table, each element of the hash holds a separate scaler value, hashes are referenced by a key
# Each pair of values in the list represents one key and its corresponding value in the hash
# %<hash-name> - % is used used and not @
# barney (key) llama (camel), betty (key) llama (value)

%words = qw(fred camel					
	    barney llama
	    betty alpaca
	    wilma alpaca
	    );

print "What is your name? ";
$name = <STDIN>;
chomp ($name);
if ($name eq "Randal") 
{
  print "Hello, Randal! How good of you to be here!\n";
} 
else 
{
  print "Hello, $name!\n";				# ordinary greeting
  $secretword = $words{$name}; 				# NEW - get the secret word $word("Betty") gets value "alpaca" etc
  print "What is the secret word? ";
  $guess = <STDIN>;
  chomp ($guess);

  while ($guess ne $secretword) 			# If $guess not equal $secretword keeps looping
  {
    print "Wrong, try again. What is the secret word? ";
    $guess = <STDIN>;
    chomp ($guess);
  }
}


