#!/usr/bin/perl -w
@words = qw(camel llama alpaca);
print "What is your name? ";
$name = <STDIN>;
chomp ($name);
if ($name eq "Randal") {
print "Hello, Randal! How good of you to be here!\n";
} else {
print "Hello, $name!\n";
# ordinary greeting
print "What is the secret word? ";
$guess = <STDIN>;
chomp ($guess);
$i = 0; # try this word first
$correct = "maybe";
# is the guess correct or not?
while ($correct eq "maybe") {	# keep checking til we know
	if ($words[$i] eq $guess) { # right?
		$correct = "yes";		# yes!
	} elsif ($i < 2) {	# more words to look at?
	$i = $i + 1;		# look at the next word next time
	} else {		# no more words, must be bad
		print "Wrong, try again. What is the secret word?";
		$guess = <STDIN>;
		chomp ($guess);
		$i = 0;	# start checking at the first word again
		}
	} # end of while not correct
} # end of "not Randal"

